# Site settings
title: Viktoras Draugelis
description: My resume
favicon: /assets/favicon.ico

baseurl: "" # the subpath of your site, e.g. /blog
url: https://resume.draugelis.dev # the base hostname & protocol for your site, e.g. http://example.com

# Color reference: https://tailwindcss.com/docs/colors
style:
  primary_color: indigo-700
  secondary_color: gray-700
  background_color: white
  text_color: black
  font: sans
